name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.5
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    max_lr: 1e-3
    base_lr: 1e-6
    weight_decay: 0.00005
    amsgrad: true

lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 20

train:
  resume_checkpoint: '/red_detection/DBNet/DBNet_fzh/phone_code_model/model_0.88.pth'
  output_path: '/red_detection/DBNet/DBNet_fzh/phone_code_model'
  epochs: 200
dataset:
  train:
    dataset:
      args:
        data_path:
          - /red_detection/DBNet/data/code_train_v2.txt
        img_mode: RGB
    loader:
      batch_size: 16
      shuffle: true
      pin_memory: true
      num_workers: 0
      collate_fn: ICDARCollectFN
  validate:
    dataset:
      args:
        data_path:
          - /red_detection/DBNet/data/code_train_v2.txt
        img_mode: RGB
        pre_processes:
          args:
            min_scale: 480
            max_scale: 480
            resize_text_polys: true
    loader:
      batch_size: 1
      shuffle: false
      pin_memory: false
      num_workers: 0
      collate_fn: ICDARCollectFN
